#!/usr/bin/env ruby

require 'optparse'
require 'net/http'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: None. This is just a test silly."

  opts.on("-t","--test MODE") do |mode|
    options[:mode] = mode
  end

  opts.on("-n NUMBER") do |number|
    options[:number] = number.to_i
  end

end.parse!

def get_url(url)
  response = Net::HTTP.get_response(URI(url))
  case response
  when Net::HTTPSuccess then
    response.body
  when Net::HTTPRedirection then
    location = response['location']
    get_url(location)
  else
    response.value
  end
end

case options[:mode]
when 'slowapi' then
  i = options[:number] || 1
  while i > 0
    puts get_url('http://slowapi.com/delay/0.3')
    i-=1
  end
else
  puts "Not a valid test!"
end
