#!/usr/bin/env ruby

require 'optparse'
require './lib/TreeParser'
require './lib/HTTPHandler'
require './lib/modes'

options = {}
ARGV << '-h' if ARGV.empty?
OptionParser.new do |opts|
  opts.banner = "Usage: developer_challenge [options]"

  opts.on("-t","--test MODE","Which test to make. Required.") do |mode|
    options[:mode] = mode
  end

  opts.on("-f","--file FILE","Triangle file for minimum_path_sum") do |file|
    options[:file] = file
  end

  opts.on("-n  NUMBER","Number of slowapi requests to make") do |number|
    options[:number] = number.to_i
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

end.parse!

options[:number] ||= 1

case options[:mode]
  when 'slowapi' then
    slowapi(options[:number])
  when 'minimum_path_sum' then
    minimum_path_sum(options[:file])
  else
    raise "Missing a valid --test argument. 'slowapi' | 'minimum_path_sum -f FILE'"
end
